# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dada/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dada/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dada/project/CMakeFiles /home/dada/project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dada/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_mutex

# Build rule for target.
test_mutex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_mutex
.PHONY : test_mutex

# fast build rule for target.
test_mutex/fast:
	$(MAKE) -f CMakeFiles/test_mutex.dir/build.make CMakeFiles/test_mutex.dir/build
.PHONY : test_mutex/fast

#=============================================================================
# Target rules for targets named test_config_log

# Build rule for target.
test_config_log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config_log
.PHONY : test_config_log

# fast build rule for target.
test_config_log/fast:
	$(MAKE) -f CMakeFiles/test_config_log.dir/build.make CMakeFiles/test_config_log.dir/build
.PHONY : test_config_log/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_backtrace

# Build rule for target.
test_backtrace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_backtrace
.PHONY : test_backtrace

# fast build rule for target.
test_backtrace/fast:
	$(MAKE) -f CMakeFiles/test_backtrace.dir/build.make CMakeFiles/test_backtrace.dir/build
.PHONY : test_backtrace/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named dzy

# Build rule for target.
dzy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dzy
.PHONY : dzy

# fast build rule for target.
dzy/fast:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/build
.PHONY : dzy/fast

dzy/config.o: dzy/config.cc.o

.PHONY : dzy/config.o

# target to build an object file
dzy/config.cc.o:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/config.cc.o
.PHONY : dzy/config.cc.o

dzy/config.i: dzy/config.cc.i

.PHONY : dzy/config.i

# target to preprocess a source file
dzy/config.cc.i:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/config.cc.i
.PHONY : dzy/config.cc.i

dzy/config.s: dzy/config.cc.s

.PHONY : dzy/config.s

# target to generate assembly for a file
dzy/config.cc.s:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/config.cc.s
.PHONY : dzy/config.cc.s

dzy/fiber.o: dzy/fiber.cc.o

.PHONY : dzy/fiber.o

# target to build an object file
dzy/fiber.cc.o:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/fiber.cc.o
.PHONY : dzy/fiber.cc.o

dzy/fiber.i: dzy/fiber.cc.i

.PHONY : dzy/fiber.i

# target to preprocess a source file
dzy/fiber.cc.i:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/fiber.cc.i
.PHONY : dzy/fiber.cc.i

dzy/fiber.s: dzy/fiber.cc.s

.PHONY : dzy/fiber.s

# target to generate assembly for a file
dzy/fiber.cc.s:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/fiber.cc.s
.PHONY : dzy/fiber.cc.s

dzy/log.o: dzy/log.cc.o

.PHONY : dzy/log.o

# target to build an object file
dzy/log.cc.o:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/log.cc.o
.PHONY : dzy/log.cc.o

dzy/log.i: dzy/log.cc.i

.PHONY : dzy/log.i

# target to preprocess a source file
dzy/log.cc.i:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/log.cc.i
.PHONY : dzy/log.cc.i

dzy/log.s: dzy/log.cc.s

.PHONY : dzy/log.s

# target to generate assembly for a file
dzy/log.cc.s:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/log.cc.s
.PHONY : dzy/log.cc.s

dzy/thread.o: dzy/thread.cc.o

.PHONY : dzy/thread.o

# target to build an object file
dzy/thread.cc.o:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/thread.cc.o
.PHONY : dzy/thread.cc.o

dzy/thread.i: dzy/thread.cc.i

.PHONY : dzy/thread.i

# target to preprocess a source file
dzy/thread.cc.i:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/thread.cc.i
.PHONY : dzy/thread.cc.i

dzy/thread.s: dzy/thread.cc.s

.PHONY : dzy/thread.s

# target to generate assembly for a file
dzy/thread.cc.s:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/thread.cc.s
.PHONY : dzy/thread.cc.s

dzy/util.o: dzy/util.cc.o

.PHONY : dzy/util.o

# target to build an object file
dzy/util.cc.o:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/util.cc.o
.PHONY : dzy/util.cc.o

dzy/util.i: dzy/util.cc.i

.PHONY : dzy/util.i

# target to preprocess a source file
dzy/util.cc.i:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/util.cc.i
.PHONY : dzy/util.cc.i

dzy/util.s: dzy/util.cc.s

.PHONY : dzy/util.s

# target to generate assembly for a file
dzy/util.cc.s:
	$(MAKE) -f CMakeFiles/dzy.dir/build.make CMakeFiles/dzy.dir/dzy/util.cc.s
.PHONY : dzy/util.cc.s

tests/test.o: tests/test.cc.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cc.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.o
.PHONY : tests/test.cc.o

tests/test.i: tests/test.cc.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cc.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.i
.PHONY : tests/test.cc.i

tests/test.s: tests/test.cc.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cc.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.s
.PHONY : tests/test.cc.s

tests/test_backtrace.o: tests/test_backtrace.cc.o

.PHONY : tests/test_backtrace.o

# target to build an object file
tests/test_backtrace.cc.o:
	$(MAKE) -f CMakeFiles/test_backtrace.dir/build.make CMakeFiles/test_backtrace.dir/tests/test_backtrace.cc.o
.PHONY : tests/test_backtrace.cc.o

tests/test_backtrace.i: tests/test_backtrace.cc.i

.PHONY : tests/test_backtrace.i

# target to preprocess a source file
tests/test_backtrace.cc.i:
	$(MAKE) -f CMakeFiles/test_backtrace.dir/build.make CMakeFiles/test_backtrace.dir/tests/test_backtrace.cc.i
.PHONY : tests/test_backtrace.cc.i

tests/test_backtrace.s: tests/test_backtrace.cc.s

.PHONY : tests/test_backtrace.s

# target to generate assembly for a file
tests/test_backtrace.cc.s:
	$(MAKE) -f CMakeFiles/test_backtrace.dir/build.make CMakeFiles/test_backtrace.dir/tests/test_backtrace.cc.s
.PHONY : tests/test_backtrace.cc.s

tests/test_config.o: tests/test_config.cc.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cc.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.o
.PHONY : tests/test_config.cc.o

tests/test_config.i: tests/test_config.cc.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cc.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.i
.PHONY : tests/test_config.cc.i

tests/test_config.s: tests/test_config.cc.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cc.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.s
.PHONY : tests/test_config.cc.s

tests/test_config_log.o: tests/test_config_log.cc.o

.PHONY : tests/test_config_log.o

# target to build an object file
tests/test_config_log.cc.o:
	$(MAKE) -f CMakeFiles/test_config_log.dir/build.make CMakeFiles/test_config_log.dir/tests/test_config_log.cc.o
.PHONY : tests/test_config_log.cc.o

tests/test_config_log.i: tests/test_config_log.cc.i

.PHONY : tests/test_config_log.i

# target to preprocess a source file
tests/test_config_log.cc.i:
	$(MAKE) -f CMakeFiles/test_config_log.dir/build.make CMakeFiles/test_config_log.dir/tests/test_config_log.cc.i
.PHONY : tests/test_config_log.cc.i

tests/test_config_log.s: tests/test_config_log.cc.s

.PHONY : tests/test_config_log.s

# target to generate assembly for a file
tests/test_config_log.cc.s:
	$(MAKE) -f CMakeFiles/test_config_log.dir/build.make CMakeFiles/test_config_log.dir/tests/test_config_log.cc.s
.PHONY : tests/test_config_log.cc.s

tests/test_fiber.o: tests/test_fiber.cc.o

.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cc.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.o
.PHONY : tests/test_fiber.cc.o

tests/test_fiber.i: tests/test_fiber.cc.i

.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cc.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.i
.PHONY : tests/test_fiber.cc.i

tests/test_fiber.s: tests/test_fiber.cc.s

.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cc.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.s
.PHONY : tests/test_fiber.cc.s

tests/test_mutex.o: tests/test_mutex.cc.o

.PHONY : tests/test_mutex.o

# target to build an object file
tests/test_mutex.cc.o:
	$(MAKE) -f CMakeFiles/test_mutex.dir/build.make CMakeFiles/test_mutex.dir/tests/test_mutex.cc.o
.PHONY : tests/test_mutex.cc.o

tests/test_mutex.i: tests/test_mutex.cc.i

.PHONY : tests/test_mutex.i

# target to preprocess a source file
tests/test_mutex.cc.i:
	$(MAKE) -f CMakeFiles/test_mutex.dir/build.make CMakeFiles/test_mutex.dir/tests/test_mutex.cc.i
.PHONY : tests/test_mutex.cc.i

tests/test_mutex.s: tests/test_mutex.cc.s

.PHONY : tests/test_mutex.s

# target to generate assembly for a file
tests/test_mutex.cc.s:
	$(MAKE) -f CMakeFiles/test_mutex.dir/build.make CMakeFiles/test_mutex.dir/tests/test_mutex.cc.s
.PHONY : tests/test_mutex.cc.s

tests/test_thread.o: tests/test_thread.cc.o

.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cc.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.o
.PHONY : tests/test_thread.cc.o

tests/test_thread.i: tests/test_thread.cc.i

.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cc.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.i
.PHONY : tests/test_thread.cc.i

tests/test_thread.s: tests/test_thread.cc.s

.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cc.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cc.s
.PHONY : tests/test_thread.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test_mutex"
	@echo "... test_config_log"
	@echo "... test_config"
	@echo "... test_fiber"
	@echo "... test_backtrace"
	@echo "... edit_cache"
	@echo "... test_thread"
	@echo "... test"
	@echo "... dzy"
	@echo "... dzy/config.o"
	@echo "... dzy/config.i"
	@echo "... dzy/config.s"
	@echo "... dzy/fiber.o"
	@echo "... dzy/fiber.i"
	@echo "... dzy/fiber.s"
	@echo "... dzy/log.o"
	@echo "... dzy/log.i"
	@echo "... dzy/log.s"
	@echo "... dzy/thread.o"
	@echo "... dzy/thread.i"
	@echo "... dzy/thread.s"
	@echo "... dzy/util.o"
	@echo "... dzy/util.i"
	@echo "... dzy/util.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_backtrace.o"
	@echo "... tests/test_backtrace.i"
	@echo "... tests/test_backtrace.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_config_log.o"
	@echo "... tests/test_config_log.i"
	@echo "... tests/test_config_log.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_mutex.o"
	@echo "... tests/test_mutex.i"
	@echo "... tests/test_mutex.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

